var TMDbAPIKey = "5a3bf778a84cd3ee3cbdef3910fc1cfc";

var mediaDb = [
    // Feature films
    {"id": "1726", "type": "movie", "title": "Iron Man"},
    {"id": "1724", "type": "movie", "title": "The Incredible Hulk"},
    {"id": "10138", "type": "movie", "title": "Iron Man 2"},
    {"id": "10195", "type": "movie", "title": "Thor"},
    {"id": "1771", "type": "movie", "title": "Captain America: The First Avenger "},
    {"id": "24428", "type": "movie", "title": "The Avengers"},
    {"id": "68721", "type": "movie", "title": "Iron Man 3"},
    {"id": "76338", "type": "movie", "title": "Thor: The Dark World"},
    {"id": "100402", "type": "movie", "title": "Captain America: The Winter Soldier"},
    {"id": "118340", "type": "movie", "title": "Guardians of the Galaxy"},
    {"id": "99861", "type": "movie", "title": "Avengers: Age of Ultron"},
    {"id": "102899", "type": "movie", "title": "Ant-Man"},
    {"id": "271110", "type": "movie", "title": "Captain America: Civil War"},
    {"id": "284052", "type": "movie", "title": "Doctor Strange"},
    {"id": "283995", "type": "movie", "title": "Guardians of the Galaxy Vol. 2"},
    {"id": "315635", "type": "movie", "title": "Spider-Man: Homecoming"},
    {"id": "284053", "type": "movie", "title": "Thor: Ragnarok"},
    {"id": "284054", "type": "movie", "title": "Black Panther"},
    {"id": "299536", "type": "movie", "title": "Avengers: Infinity War"},
    {"id": "363088", "type": "movie", "title": "Ant-Man and the Wasp"},
    {"id": "299537", "type": "movie", "title": "Captain Marvel"},
    {"id": "299534", "type": "movie", "title": "Avengers: Endgame"},
    {"id": "429617", "type": "movie", "title": "Spider-Man: Far from Home"},

    // TV shows
    {"id": "1403", "type": "tv", "title": "Marvel's Agents of S.H.I.E.L.D."},
    {"id": "61550", "type": "tv", "title": "Marvel's Agent Carter"},
    {"id": "61889", "type": "tv", "title": "Marvel's Daredevil"},
    {"id": "38472", "type": "tv", "title": "Marvel's Jessica Jones"},
    {"id": "62126", "type": "tv", "title": "Marvel's Luke Cage"},
    {"id": "62127", "type": "tv", "title": "Marvel's Iron Fist"},
    {"id": "62285", "type": "tv", "title": "Marvel's The Defenders"},
    {"id": "68716", "type": "tv", "title": "Marvel's Inhumans"},
    {"id": "67178", "type": "tv", "title": "Marvel's The Punisher"},
    {"id": "67466", "type": "tv", "title": "Marvel's Runaways"},
    {"id": "66190", "type": "tv", "title": "Marvel's Cloak & Dagger"},
    {"id": "85271", "type": "tv", "title": "WandaVision"},
    {"id": "88396", "type": "tv", "title": "The Falcon and the Winter Soldier"},
];
